version: '2.1' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: FrontEnd # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding

  express: #name of the second service
    build: BackEnd # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
